### ISSUE TITLE
tf1.4-tensorboard_advanced.py -Infinity in summary histogram for

### ISSUE THREAD

**Issue by tsingjinyun** [aymericdamien/TensorFlow-Examples#195]
Traceback (most recent call last):
  File "tensorboard_advanced.py", line 127, in <module>
    feed_dict={x: batch_xs, y: batch_ys})
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1317, in _do_run
    options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Infinity in summary histogram for: Model/relu2

**Comment by tsingjinyun** [comment]
solved by
https://github.com/aymericdamien/TensorFlow-Examples/blob/master/examples/4_Utils/tensorboard_advanced.py#L70

with tf.name_scope('Model'):
    # Build model
    pred = multilayer_perceptron(x, weights, biases)
    #add this line to avoid zero devidion
    pred = tf.log(tf.clip_by_value(pred,1e-10,1.0))
