### ISSUE TITLE
Random Forest error for tf 1.4 "Resource localhost/tree-1//N10tensorflow12tensorforest20DecisionTreeResourceE does not exist."

### ISSUE THREAD

**Issue by smsrikanthreddy** [aymericdamien/TensorFlow-Examples#208]
Hi, 
I am getting below error while running the **random forest code** in the **tensorflow 1.4 version**, even after changing the 
**"infer_op = forest_graph.inference_graph(X)" to "infer_op = forest_graph.inference_graph(X)[0]".**

**Complete Error details**:-
2017-12-08 18:16:23.961954: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2017-12-08 18:16:24.417796: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Resource localhost/tree-1//N10tensorflow12tensorforest20DecisionTreeResourceE does not exist.
2017-12-08 18:16:24.417800: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Resource localhost/tree-0//N10tensorflow12tensorforest20DecisionTreeResourceE does not exist.
2017-12-08 18:16:24.417800: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Resource localhost/tree-9//N10tensorflow12tensorforest20DecisionTreeResourceE does not exist.
2017-12-08 18:16:24.418090: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Resource localhost/tree-2//N10tensorflow12tensorforest20DecisionTreeResourceE does not exist.
2017-12-08 18:16:24.418755: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Resource localhost/tree-1//N10tensorflow12tensorforest20DecisionTreeResourceE does not exist.
2017-12-08 18:16:24.418760: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Resource localhost/tree-0//N10tensorflow12tensorforest20DecisionTreeResourceE does not exist.
2017-12-08 18:16:24.418799: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Resource localhost/tree-9//N10tensorflow12tensorforest20DecisionTreeResourceE does not exist.
2017-12-08 18:16:24.418807: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Resource localhost/tree-2//N10tensorflow12tensorforest20DecisionTreeResourceE does not exist.
2017-12-08 18:16:24.419076: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Resource localhost/tree-3//N10tensorflow12tensorforest20DecisionTreeResourceE does not exist.
2017-12-08 18:16:24.419078: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Resource localhost/tree-4//N10tensorflow12tensorforest20DecisionTreeResourceE does not exist.
2017-12-08 18:16:24.419120: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Resource localhost/tree-8//N10tensorflow12tensorforest20DecisionTreeResourceE does not exist.
2017-12-08 18:16:24.419130: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Resource localhost/tree-5//N10tensorflow12tensorforest20DecisionTreeResourceE does not exist.
2017-12-08 18:16:24.419730: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Resource localhost/tree-4//N10tensorflow12tensorforest20DecisionTreeResourceE does not exist.
2017-12-08 18:16:24.419749: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Resource localhost/tree-3//N10tensorflow12tensorforest20DecisionTreeResourceE does not exist.
2017-12-08 18:16:24.419778: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Resource localhost/tree-5//N10tensorflow12tensorforest20DecisionTreeResourceE does not exist.
2017-12-08 18:16:24.419822: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Resource localhost/tree-8//N10tensorflow12tensorforest20DecisionTreeResourceE does not exist.
2017-12-08 18:16:24.420025: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Resource localhost/tree-6//N10tensorflow12tensorforest20DecisionTreeResourceE does not exist.
2017-12-08 18:16:24.420071: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Resource localhost/tree-7//N10tensorflow12tensorforest20DecisionTreeResourceE does not exist.
2017-12-08 18:16:24.420673: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Resource localhost/tree-6//N10tensorflow12tensorforest20DecisionTreeResourceE does not exist.
2017-12-08 18:16:24.420730: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Resource localhost/tree-7//N10tensorflow12tensorforest20DecisionTreeResourceE does not exist.
Traceback (most recent call last):
  File "/Users/srikanth_m07/anaconda/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1323, in _do_call
    return fn(*args)
  File "/Users/srikanth_m07/anaconda/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1302, in _run_fn
    status, run_metadata)
  File "/Users/srikanth_m07/anaconda/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: Resource localhost/tree-1//N10tensorflow12tensorforest20DecisionTreeResourceE does not exist.
	 [[Node: TreeSize_1 = TreeSize[_device="/job:localhost/replica:0/task:0/device:CPU:0"](tree-1)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/srikanth_m07/Documents/work/tf_random_forest/tf_rf_mnist.py", line 68, in <module>
    _, l = sess.run([train_op, loss_op], feed_dict={X: batch_x, Y: batch_y})
  File "/Users/srikanth_m07/anaconda/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/Users/srikanth_m07/anaconda/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "/Users/srikanth_m07/anaconda/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1317, in _do_run
    options, run_metadata)
  File "/Users/srikanth_m07/anaconda/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Resource localhost/tree-1//N10tensorflow12tensorforest20DecisionTreeResourceE does not exist.
	 [[Node: TreeSize_1 = TreeSize[_device="/job:localhost/replica:0/task:0/device:CPU:0"](tree-1)]]

Caused by op 'TreeSize_1', defined at:
  File "/Users/srikanth_m07/Documents/work/tf_random_forest/tf_rf_mnist.py", line 38, in <module>
    loss_op = forest_graph.training_loss(X, Y)
  File "/Users/srikanth_m07/anaconda/lib/python3.5/site-packages/tensorflow/contrib/tensor_forest/python/tensor_forest.py", line 541, in training_loss
    return math_ops.negative(self.average_size(), name=name)
  File "/Users/srikanth_m07/anaconda/lib/python3.5/site-packages/tensorflow/contrib/tensor_forest/python/tensor_forest.py", line 534, in average_size
    sizes.append(self.trees[i].size())
  File "/Users/srikanth_m07/anaconda/lib/python3.5/site-packages/tensorflow/contrib/tensor_forest/python/tensor_forest.py", line 690, in size
    return model_ops.tree_size(self.variables.tree)
  File "/Users/srikanth_m07/anaconda/lib/python3.5/site-packages/tensorflow/contrib/tensor_forest/python/ops/gen_model_ops.py", line 351, in tree_size
    "TreeSize", tree_handle=tree_handle, name=name)
  File "/Users/srikanth_m07/anaconda/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/Users/srikanth_m07/anaconda/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2956, in create_op
    op_def=op_def)
  File "/Users/srikanth_m07/anaconda/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

NotFoundError (see above for traceback): Resource localhost/tree-1//N10tensorflow12tensorforest20DecisionTreeResourceE does not exist.
	 [[Node: TreeSize_1 = TreeSize[_device="/job:localhost/replica:0/task:0/device:CPU:0"](tree-1)]]

**Comment by aymericdamien** [comment]
I updated the code, it should be working now with TF 1.4: https://github.com/aymericdamien/TensorFlow-Examples/blob/master/examples/2_BasicModels/random_forest.py

**Comment by yuzhou164** [comment]
Hi aymericdamien, 
    Thank for your sharing the tensor forest code. 
   When runing this code, I encountered the following one question, Do you have any suggest?（tensorflow1.4, window7(64),python3.5）

Traceback (most recent call last):
  File "C:/Users/Administrator/Desktop/het-health-ming/sleep_stage/py3/sleep_stage_classifcation/test.py", line 35, in <module>
    forest_graph = tensor_forest.RandomForestGraphs(hparams)
  File "D:\Anaconda2\envs\py3\lib\site-packages\tensorflow\contrib\tensor_forest\python\tensor_forest.py", line 376, in __init__
    tree_variables_class=tree_variables_class)
  File "D:\Anaconda2\envs\py3\lib\site-packages\tensorflow\contrib\tensor_forest\python\tensor_forest.py", line 350, in __init__
    self.variables.append(tree_variables_class(params, i, training))
  File "D:\Anaconda2\envs\py3\lib\site-packages\tensorflow\contrib\tensor_forest\python\tensor_forest.py", line 318, in __init__
    params, '', self.get_tree_name('stats', tree_num))
  File "D:\Anaconda2\envs\py3\lib\site-packages\tensorflow\contrib\tensor_forest\python\ops\stats_ops.py", line 102, in fertile_stats_variable
    container, shared_name=name, name=name)
  File "D:\Anaconda2\envs\py3\lib\site-packages\tensorflow\contrib\tensor_forest\python\ops\gen_stats_ops.py", line 134, in fertile_stats_resource_handle_op
    shared_name=shared_name, name=name)
  File "D:\Anaconda2\envs\py3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "D:\Anaconda2\envs\py3\lib\site-packages\tensorflow\python\framework\ops.py", line 2958, in create_op
    set_shapes_for_outputs(ret)
  File "D:\Anaconda2\envs\py3\lib\site-packages\tensorflow\python\framework\ops.py", line 2209, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "D:\Anaconda2\envs\py3\lib\site-packages\tensorflow\python\framework\ops.py", line 2159, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "D:\Anaconda2\envs\py3\lib\site-packages\tensorflow\python\framework\common_shapes.py", line 627, in call_cpp_shape_fn
    require_shape_fn)
  File "D:\Anaconda2\envs\py3\lib\site-packages\tensorflow\python\framework\common_shapes.py", line 686, in _call_cpp_shape_fn_impl
    input_tensors_as_shapes, status)
  File "D:\Anaconda2\envs\py3\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: Op type not registered 'FertileStatsResourceHandleOp' in binary running on NS80011718. Make sure the Op and Kernel are registered in the binary running in this process.

**Comment by smsrikanthreddy** [comment]
Hi @yuzhou164 ,
Even I encountered the same error for windows but for mac i was able to run it without any issues.
May be it would be tensorflow library issue for windows only.
