### ISSUE TITLE
type Error 

### ISSUE THREAD

**Issue by wangzhen11aaa** [aymericdamien/TensorFlow-Examples#210]
Environment: python 3.5
tensorflow: 1.4

1. First problem is that input_data.read_data_sets() timeout. I solve it by adding 
`source_url = "http://yann.lecun.com/exdb/mnist/".`
While, the next error is:

Traceback (most recent call last):
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/pydevd.py", line 1596, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/pydevd.py", line 974, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/wangzhen/tensorflow_/custom_tensorflow/TensorFlow-Examples/examples/2_BasicModels/random_forest.py", line 51, in <module>
    correct_prediction = tf.equal(tf.argmax(infer_op, 0), tf.cast(Y, tf.int64))
  File "/usr/local/lib/python3.5/site-packages/tensorflow/python/util/deprecation.py", line 316, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/tensorflow/python/ops/math_ops.py", line 205, in argmax
    return gen_math_ops.arg_max(input, axis, name=name, output_type=output_type)
  File "/usr/local/lib/python3.5/site-packages/tensorflow/python/ops/gen_math_ops.py", line 441, in arg_max
    name=name)
  File "/usr/local/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 513, in _apply_op_helper
    raise err
  File "/usr/local/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 510, in _apply_op_helper
    preferred_dtype=default_dtype)
  File "/usr/local/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 926, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python3.5/site-packages/tensorflow/python/ops/array_ops.py", line 970, in _autopacking_conversion_function
    return _autopacking_helper(v, inferred_dtype, name or "packed")
  File "/usr/local/lib/python3.5/site-packages/tensorflow/python/ops/array_ops.py", line 912, in _autopacking_helper
    elem))
TypeError: Cannot convert a list containing a tensor of dtype <dtype: 'string'> to <dtype: 'float32'> (Tensor is: <tf.Tensor 'stack_2:0' shape=(?, 10) dtype=string>)

For this line: 
`correct_prediction = tf.equal(tf.argmax(infer_op, 0), tf.cast(Y, tf.int64))`

Any help will be appreciated, thanks.

**Comment by wangzhen11aaa** [comment]
I can get rid of this error by writing tf.equal(tf.argmax(infer_op[0], 0), tf.cast(Y, tf.int64). Because the infer_op[0] is a type of list float32. Wether do i write this right or not?

But, another error occurs: Decision Tree not found.
