### ISSUE TITLE
tensorflow.python.framework.errors_impl.NotFoundError: Op type not registered 'FertileStatsResourceHandleOp' in binary running on NS80011718.

### ISSUE THREAD

**Issue by yuzhou164** [aymericdamien/TensorFlow-Examples#216]
Hi aymericdamien,
Thank for your sharing the tensor forest code.
When runing this code, I encountered the following one question, Do you have any suggest?（tensorflow1.4, window7(64),python3.5）

Traceback (most recent call last):
File "C:/Users/Administrator/Desktop/het-health-ming/sleep_stage/py3/sleep_stage_classifcation/test.py", line 35, in 
forest_graph = tensor_forest.RandomForestGraphs(hparams)
File "D:\Anaconda2\envs\py3\lib\site-packages\tensorflow\contrib\tensor_forest\python\tensor_forest.py", line 376, in init
tree_variables_class=tree_variables_class)
File "D:\Anaconda2\envs\py3\lib\site-packages\tensorflow\contrib\tensor_forest\python\tensor_forest.py", line 350, in init
self.variables.append(tree_variables_class(params, i, training))
File "D:\Anaconda2\envs\py3\lib\site-packages\tensorflow\contrib\tensor_forest\python\tensor_forest.py", line 318, in init
params, '', self.get_tree_name('stats', tree_num))
File "D:\Anaconda2\envs\py3\lib\site-packages\tensorflow\contrib\tensor_forest\python\ops\stats_ops.py", line 102, in fertile_stats_variable
container, shared_name=name, name=name)
File "D:\Anaconda2\envs\py3\lib\site-packages\tensorflow\contrib\tensor_forest\python\ops\gen_stats_ops.py", line 134, in fertile_stats_resource_handle_op
shared_name=shared_name, name=name)
File "D:\Anaconda2\envs\py3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
op_def=op_def)
File "D:\Anaconda2\envs\py3\lib\site-packages\tensorflow\python\framework\ops.py", line 2958, in create_op
set_shapes_for_outputs(ret)
File "D:\Anaconda2\envs\py3\lib\site-packages\tensorflow\python\framework\ops.py", line 2209, in set_shapes_for_outputs
shapes = shape_func(op)
File "D:\Anaconda2\envs\py3\lib\site-packages\tensorflow\python\framework\ops.py", line 2159, in call_with_requiring
return call_cpp_shape_fn(op, require_shape_fn=True)
File "D:\Anaconda2\envs\py3\lib\site-packages\tensorflow\python\framework\common_shapes.py", line 627, in call_cpp_shape_fn
require_shape_fn)
File "D:\Anaconda2\envs\py3\lib\site-packages\tensorflow\python\framework\common_shapes.py", line 686, in _call_cpp_shape_fn_impl
input_tensors_as_shapes, status)
File "D:\Anaconda2\envs\py3\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 473, in exit
c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: Op type not registered 'FertileStatsResourceHandleOp' in binary running on NS80011718. Make sure the Op and Kernel are registered in the binary running in this process.

**Comment by sanjayraojjn** [comment]
Did anyone find any solution or reason of this problem ?

**Comment by sanjayraojjn** [comment]
For me problem resolved after I added valid list of feature columns in below line
random_forest.TensorForestEstimator(params, graph_builder_class=graph_builder_class, feature_columns=my_feature_columns)

**Comment by senthilki** [comment]
Please share the solution for this error ?

**Comment by sanjayraojjn** [comment]
I couldn't get it work out. Finally I re-implemented my solution using "sklearn.ensemble import RandomForestClassifier"

**Comment by CXSunshine** [comment]
I got the same error，but I couldn't solve it.

**Comment by RootYuan** [comment]
I got the same error. The problem remains

**Comment by pkufool** [comment]
I got the same error. （tensorflow1.7, window10(64),python3.5）

**Comment by gloomyfish1998** [comment]
I got the same error as well, someone tell me tensor_forest is not supported by windows OS with 1.8, i'm try to re-install tensorflow 1.9 now,

**Comment by kieranfraser** [comment]
I'm getting the same error (using Windows). This might be relevant - [https://github.com/tensorflow/tensorflow/issues/6791](url)
