### ISSUE TITLE
How to run "recurrent_network.py" on version 0.12.0RC? BasicLSTMCell not found

### ISSUE THREAD

**Issue by justinwm** [aymericdamien/TensorFlow-Examples#97]
I can successfully run the examples under the Neural_Network section.
When I tried to run the RNN example "recurrent_network.py" on TF version 0.12.0RC, I found that the code is not compatible.

First, there is no BasicLSTMCell, 
`Traceback (most recent call last):
  File "recurrent_network.py", line 72, in <module>
    pred = RNN(x, weights, biases)
  File "recurrent_network.py", line 64, in RNN
    lstm_cell = rnn.BasicLSTMCell(n_hidden, forget_bias=1.0)
AttributeError: 'module' object has no attribute 'BasicLSTMCell'`  

When I tried to replace it with `tf.nn.rnn_cell.BasicLSTMCell`
And still got the following error:
`Traceback (most recent call last):
  File "recurrent_network.py", line 72, in <module>
    pred = RNN(x, weights, biases)
  File "recurrent_network.py", line 67, in RNN
    outputs, states = rnn.static_rnn(lstm_cell, x, dtype=tf.float32)
AttributeError: 'module' object has no attribute 'static_rnn'`

And I have no idea what to do.. The tutorial said it fits version 0.12.0, and I can not update to the latest version since I am using a server managed by others.
Is there anyone who can help me with this and how to run this example correctly on 0.12.0RC? 

Many thanks!

**Comment by normanheckscher** [comment]
https://github.com/aymericdamien/TensorFlow-Examples/archive/0.11.zip

**Comment by justinwm** [comment]
Thanks very much!!

Thanks very for providing the older version!! @normanheckscher 

I tried to read the examples for older version in the following link, but found to be the same with the current one:
https://github.com/aymericdamien/TensorFlow-Examples/tree/0.11

**Comment by normanheckscher** [comment]
No worries.

I've just created a PR to fix the links in the older README.md file.

https://github.com/aymericdamien/TensorFlow-Examples/pull/98
